defaults:
  - _self_
hydra:
  run:
    dir: ${logdir}
_target_: agent.pretrain.train_diffusion_agent.TrainDiffusionAgent

name: ${env_name}_pre_diffusion_mlp_ta${horizon_steps}_td${denoising_steps}
logdir: ${oc.env:DPPO_LOG_DIR}/robomimic-pretrain/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}_${seed}
robomimic_env_cfg_path: cfg/robomimic/env_meta/${env_name}.json
train_dataset_path: /store/real/zhanyis/dppo/data_dir/robomimic/${env_name}/ph/train.npz
normalization_path: /store/real/zhanyis/dppo/data_dir/robomimic/${env_name}/ph/normalization.npz

seed: 42
device: cuda:0
# env: transport
env_name: can
obs_dim: 23
action_dim: 7
denoising_steps: 20
horizon_steps: 4
cond_steps: 1
act_steps: 4

env:
  n_envs: 10
  name: ${env_name}
  best_reward_threshold_for_success: 1
  max_episode_steps: 400
  save_video: false
  wrappers:
    robomimic_lowdim:
      normalization_path: ${normalization_path}
      low_dim_keys: ['robot0_eef_pos',
                    'robot0_eef_quat',
                    'robot0_gripper_qpos',
                    'object'] # same order of preprocessed observations
    multi_step:
      n_obs_steps: ${cond_steps}
      n_action_steps: ${act_steps}
      max_episode_steps: ${env.max_episode_steps}
      reset_within_step: True

wandb:
  entity: ${oc.env:DPPO_WANDB_ENTITY}
  project: robomimic-${env_name}-pretrain
  run: ${now:%H-%M-%S}_${name}

train:
  n_epochs: 8000
  batch_size: 256
  learning_rate: 1e-4
  weight_decay: 1e-6
  lr_scheduler:
    first_cycle_steps: 10000
    warmup_steps: 100
    min_lr: 1e-5
  epoch_start_ema: 20
  update_ema_freq: 10
  save_model_freq: 1000
  render:
    freq: 1
    num: 0

model:
  _target_: model.diffusion.diffusion.DiffusionModel
  predict_epsilon: True
  denoised_clip_value: 1.0
  network:
    _target_: model.diffusion.mlp_diffusion.DiffusionMLP
    time_dim: 64  # Match FlowMatchingMLP
    cond_dim: ${eval:'${obs_dim} * ${cond_steps}'}
    horizon_steps: ${horizon_steps}
    action_dim: ${action_dim}
  horizon_steps: ${horizon_steps}
  obs_dim: ${obs_dim}
  action_dim: ${action_dim}
  denoising_steps: ${denoising_steps}
  device: ${device}

ema:
  decay: 0.995

train_dataset:
  _target_: agent.dataset.sequence.StitchedSequenceDataset
  dataset_path: ${train_dataset_path}
  horizon_steps: ${horizon_steps}
  cond_steps: ${cond_steps}
  device: ${device}
  max_n_episodes: 20